config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: %i[new create destroy]
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
  resources :users
  resources :categories, only: [:show]
  get '/search', to: 'articles#search'
  
  get '/auth/:provider/callback' => "sessions#oauth"

  root to: 'articles#index'
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2 }
  validates :title, length: { maximum: 30 }
  validates :text, presence: true, length: { minimum: 10 }

  belongs_to :user, class_name: 'User', foreign_key: :AuthorId
  has_many :votes, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :categories, through: :tags
  mount_uploader :image, ImageUploader

  scope :top_voted, -> { order(vote_count: :desc).limit(1).first }
  scope :articles_by_user, ->(current_user_id) { where('"AuthorId" = ?', current_user_id) }
  scope :search, ->(search) { where('text ILIKE ?', "%#{search}%") }
  scope :include_votes, -> { includes(:votes).order(created_at: :desc) }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :access_control, only: %i[new show create edit]
  def index; end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to user_path(current_user), notice: 'Article was successfully updated.'
    else
      str = 'Article not saved!'
      new_line = '<br/>'
      @article.errors.full_messages.each do |msg|
        str << new_line
        str << msg
      end
      respond_to do |format|
        format.html { redirect_to edit_article_path(@article), alert: str }
      end
    end
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.valid? && @article.save
      if params[:category].nil?
        Tag.create(article_id: @article.id, category_id: 5)
      else
        params[:category].each do |cid|
          Tag.create(article_id: @article.id, category_id: cid)
        end
      end
      redirect_to new_article_path, notice: 'article Created Successfully'
    else
      render 'new'
    end
  end

  def search
    if params[:q].nil? || params[:q].empty?
      redirect_to articles_path, alert: 'Empty search'
    else
      @articles = Article.search(params[:q])
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image)
  end
end

app/views/articles/_form.html.erb
  <div class="px-2 py-1 mt-1 text-center">
    <% @article.errors.full_messages.each do |error| %>
        <li class="text-danger list-unstyled h5 border-bottom pb-2"><%= error %></li>
    <% end %>
  </div>

  <%= form_for @article, html: {class: 'form-horizontal p-4 bg-theme text-white'} do |f|%>
    <div class = 'form-group'>
      <%= f.label :title%>
      <%= f.text_field :title, placeholder: "article Title", class: 'form-control'%>
    </div>

    <div class = 'form-group'>
      <%= f.label :text%>
      <%= f.text_area :text, placeholder: "article Description",  class: 'form-control',  cols: "100", rows: "10"%>
    </div>
    <div class="mb-3 text-dark">
      <%= f.label :image%>
      <%= f.file_field :image %>  
    </div>

    <div class="d-flex text-dark">
        <% priority_categories().each do |category| %>
          <div class="form-group pr-4">
            <%= label_tag "#{category.name}" %>
            <%= check_box_tag "category[]", category.id %>
          </div>
        <% end %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save', class: 'btn btn-success mt-3 theme-bg-2'%>
    </div>
  <%end%>

app/views/articles/_search.html.erb
<%= form_tag("/search", :method => "get") do %>
   <%= label_tag(:q, "Search:") %>
   <div class="md-form active-pink active-pink-2 mb-3 mt-0">
    <%= text_field_tag(:q,"", class: 'form-control') %>
  </div>
   <%= submit_tag("Search", class: 'btn btn-success') %>
<% end %>

app/views/articles/_show.html.erb
<div class="mt-3 w-100 h-100 d-flex flex-wrap justify-content-center">
  <div class="col-12 col-md-5 px-0 shadow shadow-sm">
    <div class="card">
      <div class="card-img-top img-container">
        <%= image_render article %>
      </div>
      <div class="card-body">
        <div class="border-bottom border-dark pb-3">
          <h5 class="card-title"><%=article.title%></h5>
          <em>Written by <%= link_to article.user.name, user_path(article.user), class: 'btn-link'%> <%= time_ago_in_words(article.created_at)%> ago</em>
        </div>
        <p class="card-text pt-3"><%= article.text%></p>
      </div>
      <div class="d-flex pl-1 pb-1">
        <span class="mr-3">
          <%= vote_button article%>
        </span>
        <p class="h6 align-self-end">Has <%= pluralize(article.vote_count, 'vote')%></p>
      </div>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div class="row col-12 col-md-8 mx-auto shadow-sm my-5 form-border">
  <%= render 'form'%>
</div>

app/views/articles/index.html.erb
<%= sidebar_login%>
<div class="row">
  <%= link_to article_path(top_voted_article), class: 'col-12 col-md-9 px-0 bg-dark row-1-height-md  top-article' do %>
      <%= image_render top_voted_article%>
      <div class="img-description px-3 pb-2 w-100 overflow-hidden">
        <h4 class="h4 theme-color-text pb-3 font-weight-bolder  text-wrap text-break"><%= extract_title top_voted_article%></h4>
        <p class="h6 text-white font-weight-bold text-wrap text-break"><%= extract_text top_voted_article%></p>
      </div>
  <%end%>
  <div class="row col-12 col-md-3 weather_container text-white pt-md-2 px-0">
    <div class="col-6 col-md-12 weather_content_bg pt-3 pl-3">
      <h2 class="pb-1"><%= exctract_weather_info[:country] %></h2>
      <h2 class="pb-1 mb-4"><%= exctract_weather_info[:city] %></h2>
      <h4>Local Date and Time: </h4>
      <h4><%= exctract_weather_info[:time]%></h4>
    </div>
    <div class="col-6 col-md-12 weather_content_bg pt-3 pl-3">
      <i><%=image_tag(exctract_weather_info[:icon])%></i>
      <h1><sup>o</sup>C: <%= exctract_weather_info[:degree_c] %></h1>
      <h1><sup>o</sup>F: <%= exctract_weather_info[:degree_f] %></h1>
    </div>
  </div>
</div>
<div class="row categories ">
  <%priority_categories(4).each do |category|%>
    <div class="position-relative col-6 col-md-3 px-0 top-article h-100">
      <%= link_to category_path(category) do%>
        <%= image_render top_of_category category%>
        <div class="category-img-description position-absolute h-100 w-100 d-flex flex-column justify-content-between px-1">
          <h4 class="font-weight-bolder text-white underline pb-3 mt-2 mr-auto"><%= category.name%></h4>
          <h5 class="mb-4 text-white text-wrap text-break"><%= extract_title top_of_category category %></h5>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

app/views/articles/new.html.erb
<div class="row col-12 col-md-8 mx-auto justify-content-center shadow shadow-sm my-5 form-border">
  <%= render 'form'%>
</div>

app/views/articles/search.html.erb
<header class=" border-bottom text-center py-3 ">
  <h3>Found <%= pluralize(@articles.size, 'article')%></h3>
</header>
<section class="w-100 h-100 d-flex flex-wrap justify-content-center mt-2 mb-4">
  <% @articles.each do |article|%>
    <article class="border-bottom border-dark py-4">
      <%= show_article_content article %>
    </article>
  <%end%>
</section>

app/views/articles/show.html.erb
<%= show_article_content @article %>